export default async function handler(req, res) {
  // CORS
  const allowedOrigin = process.env.NODE_ENV === 'development'
    ? '*'
    : 'https://intentstack.org';
  res.setHeader('Access-Control-Allow-Origin', allowedOrigin);
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const resendKey = process.env.RESEND_API_KEY;
  const contactEmail = process.env.CONTACT_EMAIL || 'rob.kline@practicalstrategy.ai';

  if (!resendKey) {
    return res.status(500).json({ error: 'Server configuration error' });
  }

  try {
    const { intake } = req.body;

    if (!intake || !intake.complete) {
      return res.status(400).json({ error: 'Complete intake data required' });
    }

    const {
      visitor_name = 'Unknown',
      visitor_email = 'declined',
      visitor_org = 'Not provided',
      classification = 'OTHER',
      priority = 'NORMAL',
      intent_summary = 'No summary available',
      specific_questions = [],
      suggested_followup = 'Review and respond'
    } = intake;

    const priorityEmoji = {
      HIGH: '🔴',
      MEDIUM: '🟡',
      NORMAL: '🟢'
    }[priority] || '🟢';

    const classificationLabel = {
      STANDARDS_BODY: 'Standards Body Member',
      BPM_PRACTITIONER: 'BPM/Governance Practitioner',
      RESEARCHER: 'Researcher/Academic',
      COLLABORATOR: 'Potential Collaborator',
      OTHER: 'Other'
    }[classification] || 'Other';

    const questionsHtml = specific_questions.length > 0
      ? `<h3>Specific Questions</h3><ul>${specific_questions.map(q => `<li>${escapeHtml(q)}</li>`).join('')}</ul>`
      : '';

    const emailHtml = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">
          ${priorityEmoji} Intent Stack Intake — ${escapeHtml(visitor_name)}
        </h2>

        <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
          <tr><td style="padding: 6px 12px; color: #64748b; width: 140px;">Name</td><td style="padding: 6px 12px; font-weight: 600;">${escapeHtml(visitor_name)}</td></tr>
          <tr><td style="padding: 6px 12px; color: #64748b;">Email</td><td style="padding: 6px 12px;">${visitor_email === 'declined' ? '<em>Declined</em>' : `<a href="mailto:${escapeHtml(visitor_email)}">${escapeHtml(visitor_email)}</a>`}</td></tr>
          <tr><td style="padding: 6px 12px; color: #64748b;">Organization</td><td style="padding: 6px 12px;">${escapeHtml(visitor_org)}</td></tr>
          <tr><td style="padding: 6px 12px; color: #64748b;">Classification</td><td style="padding: 6px 12px;">${classificationLabel}</td></tr>
          <tr><td style="padding: 6px 12px; color: #64748b;">Priority</td><td style="padding: 6px 12px; font-weight: 600;">${priority}</td></tr>
        </table>

        <h3 style="color: #334155;">Intent Summary</h3>
        <p style="color: #475569; line-height: 1.6;">${escapeHtml(intent_summary)}</p>

        ${questionsHtml}

        <h3 style="color: #334155;">Suggested Follow-up</h3>
        <p style="color: #475569; line-height: 1.6;">${escapeHtml(suggested_followup)}</p>

        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
        <p style="color: #94a3b8; font-size: 12px;">
          Generated by Intent Stack conversational intake · intentstack.org
        </p>
      </div>
    `;

    const emailText = `Intent Stack Intake — ${visitor_name}
Priority: ${priority}
Classification: ${classificationLabel}

Name: ${visitor_name}
Email: ${visitor_email}
Organization: ${visitor_org}

Intent Summary:
${intent_summary}

${specific_questions.length > 0 ? `Specific Questions:\n${specific_questions.map(q => `- ${q}`).join('\n')}\n` : ''}
Suggested Follow-up:
${suggested_followup}
`;

    // Send via Resend
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${resendKey}`
      },
      body: JSON.stringify({
        from: 'Intent Stack <intake@intentstack.org>',
        to: [contactEmail],
        subject: `${priorityEmoji} [${priority}] Intent Stack Intake: ${visitor_name} (${classificationLabel})`,
        html: emailHtml,
        text: emailText,
        reply_to: visitor_email !== 'declined' ? visitor_email : undefined
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Resend API error:', response.status, errorText);
      return res.status(502).json({ error: 'Failed to send email' });
    }

    return res.status(200).json({ success: true });

  } catch (err) {
    console.error('Submit handler error:', err);
    return res.status(500).json({ error: 'Internal server error' });
  }
}

function escapeHtml(text) {
  if (typeof text !== 'string') return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
